package entity;

import java.util.Map;

/**
 * Represents the final sentiment analysis result of a playlist, generated by the Gemini API.
 * This is a Value Object within the core Entity layer.
 */
public class SentimentResult {
    // A concise category (e.g., "Positive", "Highly Negative", "Neutral").
    private final String overallCategory;

    // The full, detailed natural language summary from Gemini.
    private final String summaryText;

    // A numerical score (e.g., 0.85 for 85% positive, or a range like -1.0 to 1.0).
    private final double numericalScore;

    // A structured breakdown, useful if Gemini provides category percentages (e.g., {"positive": 0.70, "negative": 0.30}).
    private final Map<String, Double> sentimentBreakdown;

    /**
     * Constructs a SentimentResult value object.
     *
     * @param overallCategory A high-level assessment of the sentiment.
     * @param numericalScore A quantitative measure of the sentiment.
     * @param summaryText The full text analysis generated by the LLM.
     * @param sentimentBreakdown A map showing the distribution of sentiment categories (e.g., song counts or percentage).
     */
    public SentimentResult(
            String overallCategory,
            double numericalScore,
            String summaryText,
            Map<String, Double> sentimentBreakdown) {
        this.overallCategory = overallCategory;
        this.numericalScore = numericalScore;
        this.summaryText = summaryText;
        this.sentimentBreakdown = sentimentBreakdown;
    }

    // --- Getters (making the object effectively immutable) ---

    public String getOverallCategory() {
        return overallCategory;
    }

    public double getNumericalScore() {
        return numericalScore;
    }

    public String getSummaryText() {
        return summaryText;
    }

    public Map<String, Double> getSentimentBreakdown() {
        // Return a copy or unmodifiable map to maintain immutability
        return Map.copyOf(sentimentBreakdown);
    }

    /**
     * Provides a brief string representation for debugging or quick display.
     */
    @Override
    public String toString() {
        return overallCategory + " (" + String.format("%.2f", numericalScore) + ")";
    }
}