package entity;

import java.util.Collections;
import java.util.Map;

/**
 * Represents the final analysis result of a playlist, generated by the Gemini API.
 * This entity has been updated to focus on descriptive "vibe" analysis, now named "sentiment."
 */
public class SentimentResult {
    private final String sentimentWord;
    private final String sentimentExplanation;

    /**
     * Constructs a SentimentResult value object.
     *
     * @param sentimentWord A high-level, descriptive word or two for the playlist's feel.
     * @param sentimentExplanation The full text analysis generated by the LLM explaining the feeling.
     */
    public SentimentResult(
            String sentimentWord,
            String sentimentExplanation) {
        this.sentimentWord = sentimentWord;
        this.sentimentExplanation = sentimentExplanation;
    }

    public String getSentimentWord() {
        return sentimentWord;
    }

    public String getSentimentExplanation() {
        return sentimentExplanation;
    }
}